version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
     - "54321:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: generic
      POSTGRES_PASSWORD: generic
